"use client";

import {
  AlertCircle, BarChart3, Bell, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, ClipboardList,
  Copy, Download, Edit3, FileJson, Filter, Home, Inbox, KanbanSquare, Lightbulb, Menu, MoreHorizontal,
  Plus, RotateCcw, Search, Settings as SettingsIcon, Sparkles, Trash2, Upload, X,
} from "lucide-react";
import { useMemo, useRef, useState } from "react";
import { addDays, addMonths, endOfMonth, endOfWeek, format, isSameDay, isSameMonth, parseISO, startOfMonth, startOfWeek, subMonths } from "date-fns";
import { ru } from "date-fns/locale";
import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ContentForm } from "./content-form";
import { MetricsForm } from "./metrics-form";
import { Button, Card, Confirm, Empty, Field, inputClass, Modal, Toast } from "./ui";
import { usePlannerStore } from "@/lib/store";
import { CONTENT_TYPES, STATUSES, type AppData, type ContentItem, type Idea, type Status } from "@/lib/types";
import { csv, download, engagement, formatNumber, leadConversion, platformById, uid } from "@/lib/utils";

type Tab = "Главная" | "Календарь" | "Доска" | "Банк идей" | "Аналитика" | "Настройки";
const tabs: { name: Tab; icon: typeof Home }[] = [
  { name: "Главная", icon: Home }, { name: "Календарь", icon: CalendarDays }, { name: "Доска", icon: KanbanSquare },
  { name: "Банк идей", icon: Lightbulb }, { name: "Аналитика", icon: BarChart3 }, { name: "Настройки", icon: SettingsIcon },
];
const statusColors: Record<Status, string> = { "Идея": "bg-stone-100 text-stone-700", "Пишу текст": "bg-blue-50 text-blue-700", "Нужен визуал": "bg-purple-50 text-purple-700", "Готово": "bg-emerald-50 text-emerald-700", "Запланировано": "bg-orange-50 text-orange-700", "Опубликовано": "bg-teal-50 text-teal-700", "Использовать повторно": "bg-pink-50 text-pink-700" };
const contentColors: Record<string, string> = { "Полезный": "#f97316", "Экспертный": "#0ea5e9", "Вовлекающий": "#8b5cf6", "Личный": "#14b8a6", "Продающий": "#ec4899" };

function dateLabel(value: string) { try { return format(parseISO(value), "d MMM", { locale: ru }); } catch { return value; } }

export function PlannerApp() {
  const { data, setData, ready, reset, isCloud, userEmail, signIn, signOut } = usePlannerStore();
  const [tab, setTab] = useState<Tab>("Главная");
  const [mobileMenu, setMobileMenu] = useState(false);
  const [editor, setEditor] = useState<{ item?: ContentItem; date?: string } | null>(null);
  const [metricsItem, setMetricsItem] = useState<ContentItem | null>(null);
  const [deleteItem, setDeleteItem] = useState<ContentItem | null>(null);
  const [toast, setToast] = useState("");

  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 3000); };
  const saveItem = (item: ContentItem) => {
    setData((d) => ({ ...d, items: d.items.some((x) => x.id === item.id) ? d.items.map((x) => x.id === item.id ? item : x) : [...d.items, item] }));
    setEditor(null); notify("Материал сохранён");
  };
  const removeItem = (id: string) => { setData((d) => ({ ...d, items: d.items.filter((x) => x.id !== id), funnels: d.funnels.map((f) => ({ ...f, itemIds: f.itemIds.filter((x) => x !== id) })) })); setDeleteItem(null); notify("Материал удалён"); };
  const duplicateItem = (item: ContentItem) => { const copy = structuredClone(item); copy.id = uid("content"); copy.title += " — копия"; copy.variants = copy.variants.map((v) => ({ ...v, id: uid("variant") })); setData((d) => ({ ...d, items: [...d.items, copy] })); notify("Создана копия"); };
  const updateStatus = (id: string, status: Status) => setData((d) => ({ ...d, items: d.items.map((x) => x.id === id ? { ...x, status, variants: x.variants.map((v) => ({ ...v, status })) } : x) }));

  if (!ready) return <div className="grid min-h-screen place-items-center bg-cream"><div className="text-center"><div className="mx-auto mb-3 size-12 animate-pulse rounded-2xl bg-orange-400"/><p className="text-sm text-stone-500">Загружаем ваш контент-план…</p></div></div>;
  if (isCloud && !userEmail) return <AuthScreen signIn={signIn}/>;

  const shared = { data, setData, edit: (item: ContentItem) => setEditor({ item }), remove: setDeleteItem, duplicate: duplicateItem, notify };
  return <main className="min-h-screen bg-cream px-3 py-3 sm:px-5 sm:py-5 lg:px-8">
    <header className="mx-auto max-w-[1500px] rounded-[1.75rem] bg-gradient-to-r from-amber-300 via-orange-400 to-orange-500 px-4 py-4 text-stone-900 shadow-soft sm:px-6 lg:px-8">
      <div className="flex items-center justify-between gap-3">
        <button className="flex items-center gap-3 text-left" onClick={() => setTab("Главная")}><span className="grid size-11 place-items-center rounded-2xl bg-white/90 text-xl shadow-sm">🍊</span><span><strong className="block text-lg font-black leading-tight">Апельсин</strong><span className="hidden text-xs font-semibold text-stone-700 sm:block">контент без суеты</span></span></button>
        <nav className="hidden items-center gap-1 rounded-2xl bg-white/30 p-1 lg:flex" aria-label="Основная навигация">{tabs.slice(0, 5).map(({ name, icon: Icon }) => <button key={name} onClick={() => setTab(name)} className={`flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-bold transition ${tab === name ? "bg-white text-orange-600 shadow-sm" : "text-stone-800 hover:bg-white/40"}`}><Icon size={16}/>{name}</button>)}</nav>
        <div className="flex items-center gap-2"><span className="hidden rounded-xl bg-white/30 px-3 py-2 text-xs font-bold md:block">{isCloud ? userEmail : "Демо-режим"}</span>{isCloud && <button onClick={() => void signOut()} className="hidden rounded-xl bg-white/50 px-3 py-2 text-xs font-bold md:block">Выйти</button>}<button onClick={() => setTab("Настройки")} className="hidden rounded-xl bg-white/80 p-2.5 text-orange-600 sm:block" aria-label="Настройки"><SettingsIcon size={19}/></button><button onClick={() => setMobileMenu(!mobileMenu)} className="rounded-xl bg-white/80 p-2.5 lg:hidden" aria-label="Меню">{mobileMenu ? <X size={20}/> : <Menu size={20}/>}</button></div>
      </div>
      {mobileMenu && <nav className="mt-3 grid grid-cols-2 gap-2 rounded-2xl bg-white/30 p-2 sm:grid-cols-3 lg:hidden">{tabs.map(({ name, icon: Icon }) => <button key={name} onClick={() => { setTab(name); setMobileMenu(false); }} className={`flex items-center gap-2 rounded-xl px-3 py-2.5 text-sm font-bold ${tab === name ? "bg-white text-orange-600" : "bg-white/30"}`}><Icon size={16}/>{name}</button>)}</nav>}
    </header>
    <div className={`mx-auto mt-3 max-w-[1500px] rounded-2xl border px-4 py-2.5 text-center text-xs font-semibold sm:text-sm ${isCloud ? "border-emerald-200 bg-emerald-50 text-emerald-900" : "border-amber-200 bg-amber-50 text-amber-900"}`}>{isCloud ? "Облачный режим: изменения синхронизируются через Supabase" : "Демонстрационный режим: данные сохраняются только в этом браузере"}</div>
    <div className="mx-auto max-w-[1500px] py-6">
      {tab === "Главная" && <Dashboard {...shared} onCreate={() => setEditor({})} onTab={setTab}/>} 
      {tab === "Календарь" && <CalendarView {...shared} onCreate={(date) => setEditor({ date })}/>} 
      {tab === "Доска" && <Board {...shared} updateStatus={updateStatus}/>} 
      {tab === "Банк идей" && <Ideas {...shared} onCreateContent={(item) => setEditor({ item })}/>} 
      {tab === "Аналитика" && <Analytics data={data} editMetrics={setMetricsItem}/>} 
      {tab === "Настройки" && <Settings data={data} setData={setData} reset={reset} notify={notify}/>} 
    </div>
    <button onClick={() => setEditor({})} className="fixed bottom-5 right-5 grid size-14 place-items-center rounded-2xl bg-orange-500 text-white shadow-xl hover:bg-orange-600 sm:hidden" aria-label="Создать материал"><Plus/></button>
    {editor && <Modal title={editor.item ? "Редактировать материал" : "Новый материал"} onClose={() => setEditor(null)} wide><ContentForm data={data} initial={editor.item} initialDate={editor.date} onSave={saveItem} onCancel={() => setEditor(null)}/></Modal>}
    {metricsItem && <Modal title={`Показатели: ${metricsItem.title}`} onClose={() => setMetricsItem(null)}><MetricsForm item={metricsItem} onCancel={() => setMetricsItem(null)} onSave={(metrics) => { setData((d) => ({ ...d, items: d.items.map((x) => x.id === metricsItem.id ? { ...x, metrics } : x) })); setMetricsItem(null); notify("Показатели обновлены"); }}/></Modal>}
    {deleteItem && <Confirm title="Удалить материал?" text={`«${deleteItem.title}» и все версии для соцсетей будут удалены. Отменить действие будет нельзя.`} onClose={() => setDeleteItem(null)} onConfirm={() => removeItem(deleteItem.id)}/>} 
    {toast && <Toast message={toast} onClose={() => setToast("")}/>} 
  </main>;
}

function AuthScreen({ signIn }: { signIn: (email: string) => Promise<string | null> }) {
  const [email, setEmail] = useState(""); const [sent, setSent] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  return <main className="grid min-h-screen place-items-center bg-cream p-4"><Card className="w-full max-w-md p-7 sm:p-9"><div className="mb-6 grid size-14 place-items-center rounded-2xl bg-gradient-to-br from-amber-300 to-orange-500 text-2xl shadow-soft">🍊</div><p className="text-xs font-black uppercase tracking-widest text-orange-500">Облачный контент-планер</p><h1 className="mt-1 text-3xl font-black tracking-tight">Войдите в «Апельсин»</h1>{sent ? <div className="mt-5 rounded-2xl bg-emerald-50 p-4 text-sm text-emerald-900"><strong>Письмо отправлено</strong><p className="mt-1">Откройте ссылку для входа на этом устройстве. После входа данные будут синхронизироваться через Supabase.</p></div> : <form className="mt-6 grid gap-4" onSubmit={async (e) => { e.preventDefault(); setLoading(true); setError(""); const message = await signIn(email); setLoading(false); if (message) setError(message); else setSent(true); }}><Field label="Электронная почта"><input type="email" required autoFocus className={inputClass} value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com"/></Field>{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<Button disabled={loading}>{loading ? "Отправляем…" : "Получить ссылку для входа"}</Button><p className="text-center text-xs text-stone-400">Пароль не нужен. Мы отправим безопасную одноразовую ссылку.</p></form>}</Card></main>;
}

type Shared = { data: AppData; setData: ReturnType<typeof usePlannerStore>["setData"]; edit: (item: ContentItem) => void; remove: (item: ContentItem) => void; duplicate: (item: ContentItem) => void; notify: (message: string) => void };

function PageTitle({ eyebrow, title, text, action }: { eyebrow: string; title: string; text: string; action?: React.ReactNode }) {
  return <div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-1 text-xs font-black uppercase tracking-[.18em] text-orange-500">{eyebrow}</p><h1 className="text-3xl font-black tracking-[-.04em] sm:text-4xl">{title}</h1><p className="mt-2 max-w-2xl text-sm text-stone-500 sm:text-base">{text}</p></div>{action}</div>;
}

function ItemCard({ item, data, edit, remove, duplicate, compact = false }: { item: ContentItem; data: AppData; edit: Shared["edit"]; remove: Shared["remove"]; duplicate: Shared["duplicate"]; compact?: boolean }) {
  return <article className="group rounded-2xl border border-stone-100 bg-white p-4 shadow-sm transition hover:border-orange-200 hover:shadow-md" onDoubleClick={() => edit(item)}>
    <div className="flex items-start justify-between gap-2"><div className="min-w-0"><span className={`inline-flex rounded-full px-2 py-1 text-[10px] font-bold ${statusColors[item.status]}`}>{item.status}</span><h3 className="mt-2 line-clamp-2 font-extrabold leading-snug">{item.title}</h3></div><div className="flex shrink-0 opacity-100 sm:opacity-0 sm:group-hover:opacity-100"><button onClick={() => edit(item)} className="rounded-lg p-1.5 text-stone-400 hover:bg-orange-50 hover:text-orange-600" aria-label="Редактировать"><Edit3 size={15}/></button><button onClick={() => duplicate(item)} className="rounded-lg p-1.5 text-stone-400 hover:bg-orange-50 hover:text-orange-600" aria-label="Копировать"><Copy size={15}/></button><button onClick={() => remove(item)} className="rounded-lg p-1.5 text-stone-400 hover:bg-red-50 hover:text-red-600" aria-label="Удалить"><Trash2 size={15}/></button></div></div>
    {!compact && <p className="mt-2 line-clamp-2 text-sm text-stone-500">{item.idea || item.notes || "Описание пока не добавлено"}</p>}
    <div className="mt-3 flex flex-wrap items-center justify-between gap-2"><div className="flex -space-x-1">{item.variants.slice(0, 4).map((v) => <span key={v.id} title={platformById(data, v.platformId)?.name} className="size-3 rounded-full border-2 border-white" style={{ background: platformById(data, v.platformId)?.color }}/>)}</div><span className="text-xs font-semibold text-stone-400">{dateLabel(item.date)} · {item.time}</span></div>
  </article>;
}

function Dashboard({ data, edit, remove, duplicate, onCreate, onTab }: Shared & { onCreate: () => void; onTab: (tab: Tab) => void }) {
  const today = new Date().toISOString().slice(0, 10); const week = addDays(new Date(), 7).toISOString().slice(0, 10); const month = new Date().toISOString().slice(0, 7);
  const todayItems = data.items.filter((x) => x.date === today); const weekItems = data.items.filter((x) => x.date >= today && x.date <= week);
  const published = data.items.filter((x) => x.status === "Опубликовано" && x.date.startsWith(month)); const totalLeads = data.items.reduce((s, x) => s + x.metrics.leads, 0); const avgReach = Math.round(data.items.reduce((s, x) => s + x.metrics.reach, 0) / Math.max(1, data.items.length));
  const best = [...data.items].sort((a, b) => b.metrics.reach - a.metrics.reach)[0];
  const metrics = [{ label: "Сегодня", value: todayItems.length, icon: CalendarDays }, { label: "На неделю", value: weekItems.length, icon: ClipboardList }, { label: "В работе", value: data.items.filter((x) => ["Пишу текст", "Нужен визуал"].includes(x.status)).length, icon: Edit3 }, { label: "Готово", value: data.items.filter((x) => x.status === "Готово").length, icon: CheckCircle2 }, { label: "За месяц", value: published.length, icon: Sparkles }, { label: "Заявки", value: totalLeads, icon: Inbox }, { label: "Средний охват", value: formatNumber(avgReach), icon: BarChart3 }];
  const actualBalance = CONTENT_TYPES.map((type) => ({ name: type, value: data.items.filter((x) => x.type === type).length || 0.01, color: contentColors[type] }));
  const alerts = [
    ...(data.items.some((x) => x.date === addDays(new Date(), 1).toISOString().slice(0, 10) && !["Готово", "Запланировано"].includes(x.status)) ? ["На завтра нет готовой публикации"] : []),
    ...data.items.filter((x) => x.deadline < today && !["Опубликовано", "Использовать повторно"].includes(x.status)).slice(0, 1).map(() => "Есть материал с просроченным дедлайном"),
    ...(data.items.filter((x) => x.type === "Продающий" && x.date >= addDays(new Date(), -14).toISOString().slice(0, 10)).length === 0 ? ["Давно не было продающего контента"] : []),
    ...data.items.filter((x) => x.status === "Готово" && x.date < today).slice(0, 1).map(() => "Контент готов, но ещё не опубликован"),
    ...(best && best.metrics.reach > 10000 ? [`«${best.title}» можно использовать повторно`] : []),
  ];
  return <>
    <PageTitle eyebrow="Добрый день!" title="План на виду, идеи в движении" text="Спокойно ведите контент от первого наброска до заявки на занятие." action={<Button onClick={onCreate}><Plus size={17}/> Создать материал</Button>}/>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7">{metrics.map(({ label, value, icon: Icon }) => <Card key={label} className="lift p-4"><div className="mb-3 flex size-9 items-center justify-center rounded-xl bg-orange-50 text-orange-500"><Icon size={18}/></div><strong className="block text-2xl font-black">{value}</strong><span className="text-xs font-semibold text-stone-500">{label}</span></Card>)}</div>
    {best && <Card className="mt-3 flex flex-col justify-between gap-4 bg-stone-900 text-white sm:flex-row sm:items-center"><div><span className="text-xs font-bold uppercase tracking-widest text-orange-300">Лучший материал месяца</span><h2 className="mt-1 text-xl font-black">{best.title}</h2><p className="mt-1 text-sm text-stone-300">{formatNumber(best.metrics.reach)} охват · {best.metrics.leads} заявок</p></div><Button onClick={() => edit(best)} className="shrink-0">Открыть карточку</Button></Card>}
    <div className="mt-5 grid gap-5 lg:grid-cols-[1.15fr_.85fr]">
      <Card><div className="mb-4 flex items-center justify-between"><div><h2 className="text-xl font-black">Ближайшие публикации</h2><p className="text-sm text-stone-500">На сегодня и следующие 7 дней</p></div><button onClick={() => onTab("Календарь")} className="text-sm font-bold text-orange-600">В календарь →</button></div><div className="grid gap-3">{weekItems.length ? weekItems.slice(0, 4).map((item) => <ItemCard key={item.id} item={item} data={data} edit={edit} remove={remove} duplicate={duplicate} compact/>) : <Empty title="Неделя свободна" text="Добавьте материал и выберите дату публикации."/>}</div></Card>
      <div className="grid gap-5"><Card><div className="mb-3 flex items-center gap-2"><AlertCircle className="text-orange-500" size={20}/><h2 className="text-xl font-black">Требует внимания</h2></div><div className="grid gap-2">{alerts.length ? alerts.map((alert) => <div key={alert} className="flex gap-2 rounded-xl bg-orange-50 px-3 py-2.5 text-sm font-semibold text-stone-700"><span className="mt-1 size-2 shrink-0 rounded-full bg-orange-400"/>{alert}</div>) : <p className="text-sm text-stone-500">Всё идёт по плану — критичных задач нет.</p>}</div></Card>
      <Card><h2 className="text-xl font-black">Контент-баланс</h2><p className="text-sm text-stone-500">Фактическое распределение материалов</p><div className="mt-2 h-48"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={actualBalance} dataKey="value" innerRadius={48} outerRadius={72} paddingAngle={3}>{actualBalance.map((x) => <Cell key={x.name} fill={x.color}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div><div className="grid grid-cols-2 gap-2 text-xs">{actualBalance.map((x) => <div key={x.name} className="flex items-center gap-2"><i className="size-2 rounded-full" style={{ background: x.color }}/><span>{x.name}</span></div>)}</div></Card></div>
    </div>
  </>;
}

function CalendarView({ data, setData, edit, onCreate, notify }: Shared & { onCreate: (date: string) => void }) {
  const [cursor, setCursor] = useState(new Date()); const [mode, setMode] = useState<"month" | "week">("month"); const [query, setQuery] = useState(""); const [platform, setPlatform] = useState("all");
  const rangeStart = mode === "month" ? startOfWeek(startOfMonth(cursor), { weekStartsOn: 1 }) : startOfWeek(cursor, { weekStartsOn: 1 }); const rangeEnd = mode === "month" ? endOfWeek(endOfMonth(cursor), { weekStartsOn: 1 }) : endOfWeek(cursor, { weekStartsOn: 1 });
  const days: Date[] = []; for (let day = rangeStart; day <= rangeEnd; day = addDays(day, 1)) days.push(day);
  const filtered = data.items.filter((x) => x.title.toLowerCase().includes(query.toLowerCase()) && (platform === "all" || x.variants.some((v) => v.platformId === platform)));
  const move = (item: ContentItem, date: string) => { setData((d) => ({ ...d, items: d.items.map((x) => x.id === item.id ? { ...x, date, variants: x.variants.map((v) => ({ ...v, publishDate: date })) } : x) })); notify(`Публикация перенесена на ${dateLabel(date)}`); };
  return <><PageTitle eyebrow="Редакционный ритм" title="Календарь" text="Перетаскивайте публикации между датами или открывайте карточку для точной настройки." action={<Button onClick={() => onCreate(format(cursor, "yyyy-MM-dd"))}><Plus size={17}/> Публикация</Button>}/>
    <Card className="mb-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-2"><Button variant="secondary" className="px-3" onClick={() => setCursor(mode === "month" ? subMonths(cursor, 1) : addDays(cursor, -7))} aria-label="Предыдущий период"><ChevronLeft size={18}/></Button><Button variant="secondary" onClick={() => setCursor(new Date())}>Сегодня</Button><Button variant="secondary" className="px-3" onClick={() => setCursor(mode === "month" ? addMonths(cursor, 1) : addDays(cursor, 7))} aria-label="Следующий период"><ChevronRight size={18}/></Button><h2 className="ml-2 text-lg font-black capitalize">{format(cursor, mode === "month" ? "LLLL yyyy" : "d MMMM yyyy", { locale: ru })}</h2></div><div className="flex flex-wrap gap-2"><div className="relative min-w-48 flex-1"><Search className="absolute left-3 top-3 text-stone-400" size={17}/><input value={query} onChange={(e) => setQuery(e.target.value)} className={`${inputClass} pl-9`} placeholder="Поиск"/></div><select className={`${inputClass} w-auto`} value={platform} onChange={(e) => setPlatform(e.target.value)}><option value="all">Все площадки</option>{data.platforms.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select><div className="flex rounded-xl bg-orange-50 p-1"><button onClick={() => setMode("week")} className={`rounded-lg px-3 py-2 text-sm font-bold ${mode === "week" ? "bg-white text-orange-600 shadow-sm" : "text-stone-500"}`}>Неделя</button><button onClick={() => setMode("month")} className={`rounded-lg px-3 py-2 text-sm font-bold ${mode === "month" ? "bg-white text-orange-600 shadow-sm" : "text-stone-500"}`}>Месяц</button></div></div></div></Card>
    <div className="overflow-x-auto rounded-[1.5rem] border border-orange-100 bg-white shadow-soft"><div className="grid min-w-[820px] grid-cols-7 border-b border-orange-100 bg-orange-50/60">{["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"].map((x) => <div key={x} className="p-3 text-center text-xs font-black uppercase text-stone-500">{x}</div>)}</div><div className="grid min-w-[820px] grid-cols-7">{days.map((day) => { const iso = format(day, "yyyy-MM-dd"); const items = filtered.filter((x) => x.date === iso); return <div key={iso} onDragOver={(e) => e.preventDefault()} onDrop={(e) => { const item = data.items.find((x) => x.id === e.dataTransfer.getData("text/plain")); if (item) move(item, iso); }} className={`min-h-36 border-b border-r border-orange-50 p-2 ${!isSameMonth(day, cursor) && mode === "month" ? "bg-stone-50/60 text-stone-400" : "bg-white"}`}><button onClick={() => onCreate(iso)} className={`mb-2 grid size-7 place-items-center rounded-full text-xs font-bold hover:bg-orange-100 ${isSameDay(day, new Date()) ? "bg-orange-500 text-white" : ""}`}>{format(day, "d")}</button><div className="grid gap-1.5">{items.map((item) => { const p = platformById(data, item.variants[0]?.platformId); return <button draggable onDragStart={(e) => e.dataTransfer.setData("text/plain", item.id)} key={item.id} onClick={() => edit(item)} className="rounded-lg border-l-[3px] bg-stone-50 p-2 text-left hover:bg-orange-50" style={{ borderLeftColor: p?.color ?? "#f59e0b" }}><strong className="line-clamp-2 text-[11px] leading-tight">{item.title}</strong><span className="mt-1 block text-[10px] text-stone-400">{item.time} · {item.variants[0]?.format ?? item.type}</span></button>})}</div></div>})}</div></div>
  </>;
}

function Board({ data, edit, remove, duplicate, updateStatus }: Shared & { updateStatus: (id: string, status: Status) => void }) {
  const [query, setQuery] = useState(""); const [dragging, setDragging] = useState<string | null>(null);
  const items = data.items.filter((x) => x.title.toLowerCase().includes(query.toLowerCase()));
  return <><PageTitle eyebrow="Производство контента" title="Доска" text="Статусы календаря и доски синхронизированы. Перетащите карточку, чтобы сохранить новый этап." action={<div className="relative"><Search className="absolute left-3 top-3 text-stone-400" size={17}/><input className={`${inputClass} w-full pl-9 sm:w-64`} value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Найти материал"/></div>}/>
    <div className="scrollbar-thin flex gap-4 overflow-x-auto pb-5">{STATUSES.map((status) => { const statusItems = items.filter((x) => x.status === status); return <section key={status} onDragOver={(e) => e.preventDefault()} onDrop={() => { if (dragging) { updateStatus(dragging, status); setDragging(null); } }} className="min-h-[520px] w-[290px] shrink-0 rounded-[1.4rem] border border-orange-100 bg-orange-50/50 p-3"><div className="mb-3 flex items-center justify-between px-1"><h2 className="text-sm font-black">{status}</h2><span className="grid size-7 place-items-center rounded-full bg-white text-xs font-bold text-stone-500">{statusItems.length}</span></div><div className="grid gap-3">{statusItems.map((item) => <div draggable onDragStart={() => setDragging(item.id)} onDragEnd={() => setDragging(null)} key={item.id} className={dragging === item.id ? "opacity-40" : ""}><ItemCard item={item} data={data} edit={edit} remove={remove} duplicate={duplicate}/></div>)}{!statusItems.length && <div className="rounded-2xl border border-dashed border-orange-200 p-6 text-center text-xs text-stone-400">Перетащите карточку сюда</div>}</div></section>})}</div>
  </>;
}

function Ideas({ data, setData, onCreateContent, notify }: Shared & { onCreateContent: (item: ContentItem) => void }) {
  const [query, setQuery] = useState(""); const [form, setForm] = useState<Idea | null>(null); const [deleteIdea, setDeleteIdea] = useState<Idea | null>(null);
  const blank = (): Idea => ({ id: uid("idea"), title: "", topic: "", description: "", hook: "", audience: "Родители детей 8–11 лет", category: data.settings.categories[0] ?? "", format: data.settings.formats[0] ?? "Пост", platforms: [], goal: "Охват", seasonality: "Всегда", notes: "", sourceUrl: "", createdAt: new Date().toISOString().slice(0, 10) });
  const ideas = data.ideas.filter((x) => `${x.title} ${x.topic} ${x.category}`.toLowerCase().includes(query.toLowerCase()));
  const save = (idea: Idea) => { setData((d) => ({ ...d, ideas: d.ideas.some((x) => x.id === idea.id) ? d.ideas.map((x) => x.id === idea.id ? idea : x) : [...d.ideas, idea] })); setForm(null); notify("Идея сохранена"); };
  const toContent = (idea: Idea) => onCreateContent({ id: uid("content"), title: idea.title, idea: idea.description, audience: idea.audience, category: idea.category, type: "Полезный", goal: idea.goal, funnelStage: "Привлечение внимания", date: new Date().toISOString().slice(0, 10), time: "18:00", status: "Идея", priority: "Средний", deadline: new Date().toISOString().slice(0, 10), notes: idea.notes, createdAt: new Date().toISOString().slice(0, 10), variants: idea.platforms.map((platformId) => ({ id: uid("variant"), platformId, format: idea.format, hook: idea.hook, title: idea.title, text: "", cta: "", keyword: "", visualUrl: idea.sourceUrl, publishedUrl: "", publishDate: new Date().toISOString().slice(0, 10), status: "Идея" })), metrics: { views: 0, reach: 0, reactions: 0, comments: 0, saves: 0, reposts: 0, clicks: 0, materials: 0, followers: 0, leads: 0, sales: 0 } });
  return <><PageTitle eyebrow="Творческий запас" title="Банк идей" text="Собирайте зацепки в момент вдохновения, а позже превращайте их в готовые версии." action={<Button onClick={() => setForm(blank())}><Plus size={17}/> Новая идея</Button>}/><Card className="mb-4"><div className="relative"><Search className="absolute left-3 top-3 text-stone-400" size={17}/><input className={`${inputClass} pl-9`} value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Поиск по названию, теме или рубрике"/></div></Card>
    {ideas.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{ideas.map((idea) => <Card key={idea.id} className="lift flex flex-col"><div className="mb-3 flex items-start justify-between"><div className="flex gap-1.5">{idea.platforms.map((id) => <span key={id} className="size-3 rounded-full" style={{ background: platformById(data, id)?.color }} title={platformById(data, id)?.name}/>)}</div><button className="text-stone-400"><MoreHorizontal size={19}/></button></div><h2 className="text-lg font-black">{idea.title}</h2><p className="mt-2 line-clamp-3 flex-1 text-sm text-stone-500">{idea.description}</p><div className="mt-4 flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-orange-50 px-2.5 py-1 font-semibold text-orange-700">{idea.category}</span><span className="rounded-full bg-stone-100 px-2.5 py-1 font-semibold text-stone-600">{idea.format}</span></div>{idea.hook && <div className="mt-3 rounded-xl bg-amber-50 p-3 text-sm"><strong className="text-xs text-amber-700">Хук</strong><p className="mt-1 font-semibold">{idea.hook}</p></div>}<div className="mt-4 grid grid-cols-2 gap-2"><Button variant="secondary" onClick={() => setForm(structuredClone(idea))}><Edit3 size={15}/> Изменить</Button><Button onClick={() => toContent(idea)}><CalendarDays size={15}/> В календарь</Button><Button variant="ghost" onClick={() => { const copy = structuredClone(idea); copy.id = uid("idea"); copy.title += " — копия"; setData((d) => ({ ...d, ideas: [...d.ideas, copy] })); notify("Идея скопирована"); }}><Copy size={15}/> Копия</Button><Button variant="ghost" className="text-red-600" onClick={() => setDeleteIdea(idea)}><Trash2 size={15}/> Удалить</Button></div></Card>)}</div> : <Empty title="Идей не найдено" text="Измените запрос или добавьте первую идею." action={<Button onClick={() => setForm(blank())}>Добавить идею</Button>}/>} 
    {form && <Modal title={data.ideas.some((x) => x.id === form.id) ? "Редактировать идею" : "Новая идея"} onClose={() => setForm(null)} wide><IdeaForm data={data} idea={form} onSave={save} onCancel={() => setForm(null)}/></Modal>}
    {deleteIdea && <Confirm title="Удалить идею?" text={`Идея «${deleteIdea.title}» будет удалена.`} onClose={() => setDeleteIdea(null)} onConfirm={() => { setData((d) => ({ ...d, ideas: d.ideas.filter((x) => x.id !== deleteIdea.id) })); setDeleteIdea(null); notify("Идея удалена"); }}/>}</>;
}

function IdeaForm({ data, idea: initial, onSave, onCancel }: { data: AppData; idea: Idea; onSave: (idea: Idea) => void; onCancel: () => void }) {
  const [idea, setIdea] = useState(initial); const set = (key: keyof Idea, value: Idea[keyof Idea]) => setIdea((x) => ({ ...x, [key]: value }));
  return <form onSubmit={(e) => { e.preventDefault(); if (idea.title.trim()) onSave(idea); }}><div className="grid gap-4 sm:grid-cols-2"><Field label="Название"><input autoFocus required className={inputClass} value={idea.title} onChange={(e) => set("title", e.target.value)}/></Field><Field label="Тема"><input className={inputClass} value={idea.topic} onChange={(e) => set("topic", e.target.value)}/></Field><div className="sm:col-span-2"><Field label="Описание"><textarea className={`${inputClass} min-h-20`} value={idea.description} onChange={(e) => set("description", e.target.value)}/></Field></div><Field label="Сильный хук"><input className={inputClass} value={idea.hook} onChange={(e) => set("hook", e.target.value)}/></Field><Field label="Аудитория"><input className={inputClass} value={idea.audience} onChange={(e) => set("audience", e.target.value)}/></Field><Field label="Рубрика"><select className={inputClass} value={idea.category} onChange={(e) => set("category", e.target.value)}>{data.settings.categories.map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="Формат"><select className={inputClass} value={idea.format} onChange={(e) => set("format", e.target.value)}>{data.settings.formats.map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="Цель"><input className={inputClass} value={idea.goal} onChange={(e) => set("goal", e.target.value)}/></Field><Field label="Сезонность"><input className={inputClass} value={idea.seasonality} onChange={(e) => set("seasonality", e.target.value)}/></Field><Field label="Ссылка на источник"><input type="url" className={inputClass} value={idea.sourceUrl} onChange={(e) => set("sourceUrl", e.target.value)}/></Field><Field label="Заметки"><input className={inputClass} value={idea.notes} onChange={(e) => set("notes", e.target.value)}/></Field><div className="sm:col-span-2"><Field label="Площадки"><div className="flex flex-wrap gap-2">{data.platforms.map((p) => <label key={p.id} className={`cursor-pointer rounded-xl border px-3 py-2 text-sm font-bold ${idea.platforms.includes(p.id) ? "border-orange-400 bg-orange-50" : "border-stone-200 bg-white"}`}><input type="checkbox" className="sr-only" checked={idea.platforms.includes(p.id)} onChange={() => set("platforms", idea.platforms.includes(p.id) ? idea.platforms.filter((x) => x !== p.id) : [...idea.platforms, p.id])}/><span className="mr-2 inline-block size-2 rounded-full" style={{ background: p.color }}/>{p.name}</label>)}</div></Field></div></div><div className="mt-6 flex justify-end gap-2"><Button type="button" variant="secondary" onClick={onCancel}>Отмена</Button><Button type="submit">Сохранить идею</Button></div></form>;
}

function Analytics({ data, editMetrics }: { data: AppData; editMetrics: (item: ContentItem) => void }) {
  const [platform, setPlatform] = useState("all"); const [category, setCategory] = useState("all"); const [formatFilter, setFormatFilter] = useState("all"); const [goal, setGoal] = useState("all");
  const items = data.items.filter((item) => (platform === "all" || item.variants.some((v) => v.platformId === platform)) && (category === "all" || item.category === category) && (formatFilter === "all" || item.variants.some((v) => v.format === formatFilter)) && (goal === "all" || item.goal === goal));
  const totals = items.reduce((a, x) => ({ views: a.views + x.metrics.views, reach: a.reach + x.metrics.reach, interactions: a.interactions + x.metrics.reactions + x.metrics.comments + x.metrics.saves + x.metrics.reposts, clicks: a.clicks + x.metrics.clicks, leads: a.leads + x.metrics.leads, sales: a.sales + x.metrics.sales }), { views: 0, reach: 0, interactions: 0, clicks: 0, leads: 0, sales: 0 });
  const averageViews = Math.round(totals.views / Math.max(1, items.length)); const engagementRate = totals.reach ? totals.interactions / totals.reach * 100 : 0; const clickRate = totals.reach ? totals.clicks / totals.reach * 100 : 0; const leadRate = totals.clicks ? totals.leads / totals.clicks * 100 : 0;
  const monthData = useMemo(() => {
    const result: Record<string, { month: string; views: number; reach: number; leads: number }> = {};
    items.forEach((x) => { const key = x.date.slice(0, 7); if (!result[key]) result[key] = { month: key, views: 0, reach: 0, leads: 0 }; result[key].views += x.metrics.views; result[key].reach += x.metrics.reach; result[key].leads += x.metrics.leads; });
    return Object.values(result).sort((a, b) => a.month.localeCompare(b.month)).map((x) => ({ ...x, label: format(parseISO(`${x.month}-01`), "LLL", { locale: ru }) }));
  }, [items]);
  const platformData = data.platforms.map((p) => { const relevant = items.filter((x) => x.variants.some((v) => v.platformId === p.id)); return { name: p.name, reach: relevant.reduce((s, x) => s + x.metrics.reach, 0), leads: relevant.reduce((s, x) => s + x.metrics.leads, 0), color: p.color }; });
  const best = [...items].sort((a, b) => b.metrics.reach - a.metrics.reach);
  const metrics = [{ label: "Средние просмотры", value: formatNumber(averageViews) }, { label: "Вовлечённость", value: `${engagementRate.toFixed(1)}%` }, { label: "Конверсия в переход", value: `${clickRate.toFixed(1)}%` }, { label: "Конверсия в заявку", value: `${leadRate.toFixed(1)}%` }, { label: "Заявки", value: formatNumber(totals.leads) }, { label: "Продажи", value: formatNumber(totals.sales) }];
  return <><PageTitle eyebrow="Результаты" title="Аналитика" text="Смотрите, что действительно привлекает родителей и приводит учеников." action={<Button variant="secondary" onClick={() => download("analytics.csv", "\ufeff" + csv([["Материал", "Охват", "Просмотры", "Заявки", "Продажи"], ...items.map((x) => [x.title, x.metrics.reach, x.metrics.views, x.metrics.leads, x.metrics.sales])]), "text/csv;charset=utf-8")}><Download size={17}/> CSV</Button>}/>
    <Card className="mb-4"><div className="flex flex-wrap gap-2"><span className="inline-flex items-center gap-2 px-2 text-sm font-bold text-stone-500"><Filter size={16}/> Фильтры</span><select className={`${inputClass} w-auto`} value={platform} onChange={(e) => setPlatform(e.target.value)}><option value="all">Все площадки</option>{data.platforms.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select><select className={`${inputClass} w-auto max-w-56`} value={category} onChange={(e) => setCategory(e.target.value)}><option value="all">Все рубрики</option>{data.settings.categories.map((x) => <option key={x}>{x}</option>)}</select><select className={`${inputClass} w-auto`} value={formatFilter} onChange={(e) => setFormatFilter(e.target.value)}><option value="all">Все форматы</option>{data.settings.formats.map((x) => <option key={x}>{x}</option>)}</select><select className={`${inputClass} w-auto`} value={goal} onChange={(e) => setGoal(e.target.value)}><option value="all">Все цели</option>{Array.from(new Set(data.items.map((x) => x.goal))).map((x) => <option key={x}>{x}</option>)}</select></div></Card>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{metrics.map((m) => <Card key={m.label} className="p-4"><strong className="block text-2xl font-black">{m.value}</strong><span className="text-xs font-semibold text-stone-500">{m.label}</span></Card>)}</div>
    <div className="mt-5 grid gap-5 lg:grid-cols-2"><Card><h2 className="text-xl font-black">Динамика по месяцам</h2><p className="text-sm text-stone-500">Просмотры и охват опубликованных материалов</p><div className="mt-5 h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={monthData}><CartesianGrid strokeDasharray="3 3" stroke="#f4e6d5"/><XAxis dataKey="label"/><YAxis width={45}/><Tooltip/><Legend/><Line type="monotone" dataKey="views" name="Просмотры" stroke="#f97316" strokeWidth={3}/><Line type="monotone" dataKey="reach" name="Охват" stroke="#0ea5e9" strokeWidth={3}/></LineChart></ResponsiveContainer></div></Card><Card><h2 className="text-xl font-black">Площадки</h2><p className="text-sm text-stone-500">Совокупный охват по социальным сетям</p><div className="mt-5 h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={platformData}><CartesianGrid strokeDasharray="3 3" stroke="#f4e6d5"/><XAxis dataKey="name"/><YAxis width={45}/><Tooltip/><Bar dataKey="reach" name="Охват" radius={[8, 8, 0, 0]}>{platformData.map((x) => <Cell key={x.name} fill={x.color}/>)}</Bar></BarChart></ResponsiveContainer></div></Card></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-[1.3fr_.7fr]"><Card><div className="mb-4"><h2 className="text-xl font-black">Лучшие публикации</h2><p className="text-sm text-stone-500">По охвату с учётом выбранных фильтров</p></div>{best.length ? <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead><tr className="border-b border-stone-100 text-xs uppercase text-stone-400"><th className="pb-3">Материал</th><th className="pb-3">Охват</th><th className="pb-3">Вовлечённость</th><th className="pb-3">Заявки</th><th className="pb-3"></th></tr></thead><tbody>{best.slice(0, 8).map((x) => <tr key={x.id} className="border-b border-stone-50"><td className="max-w-xs py-3 font-bold">{x.title}</td><td className="py-3">{formatNumber(x.metrics.reach)}</td><td className="py-3">{engagement(x).toFixed(1)}%</td><td className="py-3">{x.metrics.leads}</td><td className="py-3 text-right"><Button variant="ghost" className="px-2" onClick={() => editMetrics(x)}>Внести данные</Button></td></tr>)}</tbody></table></div> : <Empty title="Нет данных" text="Для выбранных фильтров публикаций пока нет."/>}</Card><Card><h2 className="text-xl font-black">Что работает</h2><p className="text-sm text-stone-500">Автоматические наблюдения</p><div className="mt-4 grid gap-3">{best.slice(0, 3).map((x, i) => <div key={x.id} className="rounded-2xl bg-orange-50 p-4"><span className="text-xs font-black text-orange-600">#{i + 1} · {x.category}</span><p className="mt-1 text-sm font-bold">{x.variants[0]?.hook || x.title}</p><p className="mt-1 text-xs text-stone-500">{x.variants[0]?.format ?? x.type} · {leadConversion(x).toFixed(1)}% в заявку</p></div>)}{best.length > 0 && <div className="rounded-2xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-800">Материалы с охватом выше 10 000 стоит адаптировать и повторить.</div>}</div></Card></div>
  </>;
}

function Settings({ data, setData, reset, notify }: { data: AppData; setData: Shared["setData"]; reset: () => void; notify: (message: string) => void }) {
  const fileRef = useRef<HTMLInputElement>(null); const [newPlatform, setNewPlatform] = useState(""); const [newCategory, setNewCategory] = useState(""); const [newFormat, setNewFormat] = useState(""); const [confirmReset, setConfirmReset] = useState(false); const [importData, setImportData] = useState<AppData | null>(null);
  const patchSettings = (values: Partial<AppData["settings"]>) => setData((d) => ({ ...d, settings: { ...d.settings, ...values } }));
  const changeBalance = (type: typeof CONTENT_TYPES[number], value: number) => patchSettings({ contentBalance: { ...data.settings.contentBalance, [type]: Math.max(0, Math.min(100, value)) } });
  const addPlatform = () => { if (!newPlatform.trim()) return; setData((d) => ({ ...d, platforms: [...d.platforms, { id: uid("platform"), name: newPlatform.trim(), color: "#f97316" }] })); setNewPlatform(""); notify("Площадка добавлена"); };
  const importFile = (file?: File) => { if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const parsed = JSON.parse(String(reader.result)) as AppData; if (!parsed.items || !parsed.settings || !parsed.platforms) throw new Error(); setImportData(parsed); } catch { notify("Не удалось прочитать резервную копию"); } }; reader.onerror = () => notify("Ошибка чтения файла"); reader.readAsText(file); };
  return <><PageTitle eyebrow="Под себя" title="Настройки" text="Площадки, рубрики, баланс и резервные копии — всё в одном месте."/>
    <div className="grid gap-5 lg:grid-cols-2"><Card><h2 className="text-xl font-black">Социальные сети</h2><p className="text-sm text-stone-500">Добавляйте свои площадки и меняйте цвета.</p><div className="mt-4 grid gap-2">{data.platforms.map((p) => <div key={p.id} className="flex items-center gap-3 rounded-xl border border-stone-100 p-3"><input type="color" value={p.color} onChange={(e) => setData((d) => ({ ...d, platforms: d.platforms.map((x) => x.id === p.id ? { ...x, color: e.target.value } : x) }))} className="size-8 cursor-pointer rounded-lg border-0 bg-transparent" aria-label={`Цвет ${p.name}`}/><input className={`${inputClass} min-h-9 flex-1`} value={p.name} onChange={(e) => setData((d) => ({ ...d, platforms: d.platforms.map((x) => x.id === p.id ? { ...x, name: e.target.value } : x) }))}/><button onClick={() => setData((d) => ({ ...d, platforms: d.platforms.filter((x) => x.id !== p.id) }))} className="p-2 text-stone-400 hover:text-red-600" aria-label="Удалить площадку"><Trash2 size={17}/></button></div>)}</div><div className="mt-3 flex gap-2"><input className={inputClass} value={newPlatform} onChange={(e) => setNewPlatform(e.target.value)} placeholder="Новая площадка" onKeyDown={(e) => { if (e.key === "Enter") { e.preventDefault(); addPlatform(); } }}/><Button onClick={addPlatform} className="shrink-0"><Plus size={16}/></Button></div></Card>
    <Card><h2 className="text-xl font-black">Контент-баланс</h2><p className="text-sm text-stone-500">Целевое распределение. Сейчас: {Object.values(data.settings.contentBalance).reduce((a, b) => a + b, 0)}%</p><div className="mt-5 grid gap-4">{CONTENT_TYPES.map((type) => <label key={type} className="grid grid-cols-[1fr_3rem] items-center gap-3 text-sm font-semibold"><span><span className="mb-1 flex justify-between"><span>{type}</span><span className="text-stone-400">{data.settings.contentBalance[type]}%</span></span><input className="w-full accent-orange-500" type="range" min="0" max="100" value={data.settings.contentBalance[type]} onChange={(e) => changeBalance(type, Number(e.target.value))}/></span><span className="size-3 rounded-full" style={{ background: contentColors[type] }}/></label>)}</div></Card>
    <Card><h2 className="text-xl font-black">Рубрики</h2><p className="text-sm text-stone-500">Редактируйте список тем для материалов.</p><div className="mt-4 flex max-h-60 flex-wrap gap-2 overflow-y-auto">{data.settings.categories.map((x) => <span key={x} className="inline-flex items-center gap-1 rounded-full bg-orange-50 px-3 py-1.5 text-xs font-bold text-orange-800">{x}<button onClick={() => patchSettings({ categories: data.settings.categories.filter((c) => c !== x) })} aria-label={`Удалить ${x}`}><X size={13}/></button></span>)}</div><div className="mt-3 flex gap-2"><input className={inputClass} value={newCategory} onChange={(e) => setNewCategory(e.target.value)} placeholder="Новая рубрика"/><Button onClick={() => { if (newCategory.trim()) { patchSettings({ categories: [...data.settings.categories, newCategory.trim()] }); setNewCategory(""); } }}><Plus size={16}/></Button></div></Card>
    <Card><h2 className="text-xl font-black">Форматы</h2><p className="text-sm text-stone-500">Доступные виды публикаций.</p><div className="mt-4 flex flex-wrap gap-2">{data.settings.formats.map((x) => <span key={x} className="inline-flex items-center gap-1 rounded-full bg-stone-100 px-3 py-1.5 text-xs font-bold text-stone-700">{x}<button onClick={() => patchSettings({ formats: data.settings.formats.filter((f) => f !== x) })}><X size={13}/></button></span>)}</div><div className="mt-3 flex gap-2"><input className={inputClass} value={newFormat} onChange={(e) => setNewFormat(e.target.value)} placeholder="Новый формат"/><Button onClick={() => { if (newFormat.trim()) { patchSettings({ formats: [...data.settings.formats, newFormat.trim()] }); setNewFormat(""); } }}><Plus size={16}/></Button></div></Card>
    <Card><h2 className="text-xl font-black">Общие настройки</h2><div className="mt-4 grid gap-4"><Field label="Часовой пояс"><select className={inputClass} value={data.settings.timezone} onChange={(e) => patchSettings({ timezone: e.target.value })}>{["Europe/Moscow", "Asia/Amman", "Asia/Yekaterinburg", "Asia/Novosibirsk"].map((x) => <option key={x}>{x}</option>)}</select></Field><label className="flex items-center justify-between rounded-xl border border-stone-100 p-3 text-sm font-semibold"><span>Неделя начинается с понедельника</span><input type="checkbox" checked={data.settings.weekStartsMonday} onChange={(e) => patchSettings({ weekStartsMonday: e.target.checked })} className="size-5 accent-orange-500"/></label><label className="flex items-center justify-between rounded-xl border border-stone-100 p-3 text-sm font-semibold"><span className="flex items-center gap-2"><Bell size={17}/> Уведомления</span><input type="checkbox" checked={data.settings.notifications} onChange={(e) => patchSettings({ notifications: e.target.checked })} className="size-5 accent-orange-500"/></label></div></Card>
    <Card><h2 className="text-xl font-black">Экспорт и резервная копия</h2><p className="text-sm text-stone-500">Скачайте данные или восстановите их из JSON.</p><div className="mt-4 grid gap-2 sm:grid-cols-2"><Button variant="secondary" onClick={() => download("content-calendar.csv", "\ufeff" + csv([["Дата", "Время", "Название", "Статус", "Рубрика"], ...data.items.map((x) => [x.date, x.time, x.title, x.status, x.category])]), "text/csv;charset=utf-8")}><CalendarDays size={16}/> Календарь CSV</Button><Button variant="secondary" onClick={() => download("content-planner-backup.json", JSON.stringify(data, null, 2), "application/json")}><FileJson size={16}/> Копия JSON</Button><Button variant="secondary" onClick={() => fileRef.current?.click()}><Upload size={16}/> Импорт JSON</Button><Button variant="danger" onClick={() => setConfirmReset(true)}><RotateCcw size={16}/> Демо-данные</Button><input ref={fileRef} className="hidden" type="file" accept="application/json,.json" onChange={(e) => importFile(e.target.files?.[0])}/></div></Card></div>
    {confirmReset && <Confirm title="Восстановить демо-данные?" text="Текущие локальные материалы, идеи и настройки будут заменены демонстрационным набором." onClose={() => setConfirmReset(false)} onConfirm={() => { reset(); setConfirmReset(false); notify("Демо-данные восстановлены"); }}/>} 
    {importData && <Modal title="Импорт резервной копии" onClose={() => setImportData(null)}><div className="rounded-2xl bg-amber-50 p-4 text-sm text-amber-900"><strong>Проверьте перед импортом</strong><p className="mt-1">Будут заменены текущие материалы, идеи, площадки и настройки. В копии найдено: {importData.items.length} материалов, {importData.ideas.length} идей, {importData.platforms.length} площадок.</p></div><div className="mt-6 flex justify-end gap-2"><Button variant="secondary" onClick={() => setImportData(null)}>Отмена</Button><Button onClick={() => { setData(importData); setImportData(null); notify("Резервная копия импортирована"); }}>Заменить данные</Button></div></Modal>}
  </>;
}
